# Auto-generated by AEGIS 4.0 on 2024-05-23
import torch
import torch.nn as nn

class AegisEvolution(nn.Module):
    def __init__(self, input_size, d_model=128, nhead=4, num_layers=3, dropout=0.2):
        super(AegisEvolution, self).__init__()

        # Feature Embedding Layer (Dense -> High Dim)
        self.feature_embedding = nn.Sequential(
            nn.Linear(input_size, d_model),
            nn.LayerNorm(d_model),
            nn.GELU()
        )

        # Transformer Encoder Block (Self-Attention + FeedForward)
        # batch_first=True ensures input is (Batch, Seq, Feature)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=d_model*4,
            dropout=dropout,
            batch_first=True,
            activation='gelu'
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Final Output Head (Value Projection)
        self.head = nn.Sequential(
            nn.Linear(d_model, 64),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        # x: (Batch, Input_Size)

        # 1. Embed Features
        x = self.feature_embedding(x) # -> (Batch, d_model)

        # 2. Add Sequence Dimension for Transformer (SeqLen=1)
        x = x.unsqueeze(1) # -> (Batch, 1, d_model)

        # 3. Apply Transformer Encoder
        x = self.transformer_encoder(x) # -> (Batch, 1, d_model)

        # 4. Remove Sequence Dimension
        x = x.squeeze(1) # -> (Batch, d_model)

        # 5. Output Probability
        return self.head(x)
