# Auto-generated by AEGIS 4.0 on 2026-02-19 23:23:39.750459
import torch
import torch.nn as nn
import math

import torch
import torch.nn as nn
import math

class AegisEvolution(nn.Module):
    """
    A Transformer-based model optimized for PyTorch MPS acceleration on MacBook M5.
    This model adapts the Transformer architecture for processing flat feature vectors,
    treating the entire embedded input as a single sequence token.
    """
    def __init__(self, input_size: int, output_size: int = 1, d_model: int = 128, nhead: int = 4,
                 num_encoder_layers: int = 3, dim_feedforward: int = 512, dropout: float = 0.1):
        """
        Initializes the AegisEvolution model.

        Args:
            input_size (int): The number of input features (e.g., length of the flat feature vector).
            output_size (int): The dimension of the model's output (e.g., number of classes, or 1 for regression).
            d_model (int): The dimension of the hidden states (embedding dimension) in the Transformer.
                           Must be divisible by nhead.
            nhead (int): The number of attention heads in the MultiHeadAttention mechanism.
            num_encoder_layers (int): The number of sub-encoder layers in the TransformerEncoder.
            dim_feedforward (int): The dimension of the feedforward network model in the Transformer encoder layer.
            dropout (float): The dropout value.
        """
        super().__init__()

        if d_model % nhead != 0:
            raise ValueError(f"d_model ({d_model}) must be divisible by nhead ({nhead})")

        self.d_model = d_model
        
        # 1. Input embedding layer: Projects the flat input_size features into the d_model dimension.
        # This treats the entire input vector as a single, complex entity to be embedded.
        self.embedding_layer = nn.Linear(input_size, d_model)
        
        # Transformer Encoder setup
        # Using batch_first=False as it's the default for TransformerEncoder and
        # aligns with the sequence-first expected shape (Seq_Len, Batch, Feature_Dim).
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, 
            nhead=nhead, 
            dim_feedforward=dim_feedforward, 
            dropout=dropout, 
            batch_first=False
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer, 
            num_layers=num_encoder_layers
        )
        
        # Final output layer: Projects the Transformer's output to the desired output_size.
        self.output_layer = nn.Linear(d_model, output_size)

        # Initialize weights for potentially better training stability and performance.
        self._init_weights()

    def _init_weights(self):
        """Initializes weights using Xavier uniform distribution."""
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass for the AegisEvolution model.

        Args:
            x (torch.Tensor): Input tensor of shape (Batch_Size, Input_Size).

        Returns:
            torch.Tensor: Output tensor of shape (Batch_Size, Output_Size).
        """
        # 1. Input shape handling: (Batch_Size, Input_Size)
        # Apply the embedding layer to project input features to d_model.
        # Shape: (Batch_Size, Input_Size) -> (Batch_Size, d_model)
        embedded_features = self.embedding_layer(x)

        # 2. Reshape for TransformerEncoder: (Batch_Size, d_model) -> (Seq_Len, Batch_Size, d_model)
        # We treat the entire embedded vector as a single "token" in a sequence.
        # Therefore, Seq_Len = 1.
        src = embedded_features.unsqueeze(0) # Shape: (1, Batch_Size, d_model)

        # 3. Pass through the Transformer Encoder.
        # The TransformerEncoder expects input `src` of shape (S, N, E)
        # where S is sequence length, N is batch size, E is embedding dimension.
        # Output shape is also (1, Batch_Size, d_model).
        transformer_output = self.transformer_encoder(src)

        # 4. Process Transformer output for the final layer.
        # Remove the sequence dimension: (1, Batch_Size, d_model) -> (Batch_Size, d_model)
        final_features = transformer_output.squeeze(0)

        # 5. Apply the final linear layer for the desired output.
        # Shape: (Batch_Size, d_model) -> (Batch_Size, Output_Size)
        output = self.output_layer(final_features)

        return output