# Auto-generated by AEGIS 4.0 on 2026-02-19 14:38:23.148955
import torch
import torch.nn as nn

import torch
import torch.nn as nn
import math

class FinancialPositionalEncoding(nn.Module):
    """
    Standard sinusoidal positional encoding, adapted for financial time series.
    Adds positional information to the input embeddings, crucial for sequence models
    to understand the order of elements.
    """
    def __init__(self, d_model: int, max_len: int = 5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0) # (1, max_len, d_model)
        self.register_buffer('pe', pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Tensor, shape [batch_size, seq_len, embedding_dim]
        Returns:
            Tensor, shape [batch_size, seq_len, embedding_dim] with positional encoding added.
        """
        # Ensure pe is on the same device as x and only take the necessary part
        return x + self.pe[:, :x.size(1)].to(x.device)

class GatedLinearUnit(nn.Module):
    """
    A Gated Linear Unit (GLU) as used in Temporal Fusion Transformers (TFT).
    It applies a linear transformation followed by a split, one part is activated
    by sigmoid and element-wise multiplied with the other part, effectively
    creating a gating mechanism.
    """
    def __init__(self, input_size: int, output_size: int):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size * 2)
        self.glu = nn.GLU()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.glu(self.linear(x))

class FinancialAttention(nn.MultiheadAttention):
    """
    Multi-Head Self-Attention mechanism specialized for financial time-series.
    The specialization primarily comes from enforcing causal masking by default,
    which prevents the model from attending to future data points when making
    predictions for the current time step. This is critical for preventing data
    leakage in sequential financial data.
    """
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = 0.0, bias: bool = True):
        super().__init__(embed_dim, num_heads, dropout=dropout, bias=bias, batch_first=True)

    def forward(self, query: torch.Tensor, key: torch.Tensor, value: torch.Tensor,
                attn_mask: torch.Tensor = None, key_padding_mask: torch.Tensor = None) -> torch.Tensor:
        """
        Args:
            query, key, value: Input tensors (batch_size, seq_len, embed_dim).
            attn_mask: An optional mask to prevent attention to certain positions.
                       If None, a causal mask is generated.
            key_padding_mask: An optional mask to prevent attention to padded key tokens.
        Returns:
            Output tensor from the attention mechanism (batch_size, seq_len, embed_dim).
        """
        seq_len = query.size(1)
        if attn_mask is None:
            # Generate causal mask to prevent attending to future time steps
            attn_mask = self.generate_causal_mask(seq_len).to(query.device)
        
        # PyTorch's MultiheadAttention expects query, key, value as (batch_size, seq_len, embed_dim)
        # when batch_first=True. attn_mask should be (seq_len, seq_len).
        return super().forward(query, key, value, attn_mask=attn_mask, key_padding_mask=key_padding_mask, need_weights=False)[0]

    @staticmethod
    def generate_causal_mask(seq_len: int) -> torch.Tensor:
        """
        Generates a causal mask (upper triangular matrix) to prevent attention to future time steps.
        """
        # Create an upper triangular matrix of ones, then fill allowed values with 0.0 and masked with -inf.
        mask = (torch.triu(torch.ones(seq_len, seq_len)) == 1).transpose(0, 1)
        mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
        return mask

class TransformerEncoderBlock(nn.Module):
    """
    A single encoder block of the Transformer, incorporating Multi-Head Self-Attention,
    Gated Linear Unit (GLU) for the feed-forward network, residual connections,
    and layer normalization, inspired by TFT and standard Transformer architectures.
    """
    def __init__(self, d_model: int, num_heads: int, ff_dim: int, dropout: float = 0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(d_model)
        self.attention = FinancialAttention(d_model, num_heads, dropout=dropout)
        self.dropout1 = nn.Dropout(dropout)

        self.norm2 = nn.LayerNorm(d_model)
        # Feed-forward network with GLU for non-linearity, inspired by TFT
        self.ffn = nn.Sequential(
            nn.Linear(d_model, ff_dim),
            GatedLinearUnit(ff_dim, d_model), # GLU maps ff_dim back to d_model
            nn.Dropout(dropout)
        )
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, causal_mask: torch.Tensor = None) -> torch.Tensor:
        """
        Args:
            x: Input tensor (batch_size, seq_len, d_model).
            causal_mask: Mask to apply to the attention mechanism.
        Returns:
            Output tensor after one encoder block (batch_size, seq_len, d_model).
        """
        # Self-attention sub-layer with residual connection and layer normalization
        norm_x = self.norm1(x)
        attn_output = self.attention(norm_x, norm_x, norm_x, attn_mask=causal_mask)
        x = x + self.dropout1(attn_output) # Residual connection

        # Feed-forward sub-layer with residual connection and layer normalization
        norm_x = self.norm2(x)
        ffn_output = self.ffn(norm_x)
        x = x + self.dropout2(ffn_output) # Residual connection
        return x

class AegisEvolution(nn.Module):
    """
    AegisEvolution: An improved PyTorch model for financial time-series forecasting,
    leveraging a Transformer/TFT-like architecture. It incorporates:
    - Input embeddings and positional encodings.
    - Multiple TransformerEncoderBlocks with residual connections and layer normalization.
    - FinancialAttention, a specialized Multi-Head Self-Attention with causal masking.
    - Gated Linear Units (GLU) within the feed-forward networks, inspired by TFT.
    - Designed for efficient computation on Apple Silicon (M-series) with MPS acceleration.
    """
    def __init__(self, input_size: int, output_size: int = 1, model_dim: int = 128,
                 num_heads: int = 8, num_layers: int = 4, ff_dim: int = 512,
                 dropout: float = 0.1, sequence_length: int = 60):
        """
        Initializes the AegisEvolution model.

        Args:
            input_size (int): Dimension of each time step's feature vector.
            output_size (int): Dimension of the output prediction (e.g., 1 for regression).
            model_dim (int): Dimensionality of the model's internal representations (embedding dimension).
            num_heads (int): Number of attention heads in Multi-Head Attention.
            num_layers (int): Number of TransformerEncoderBlocks in the encoder stack.
            ff_dim (int): Hidden dimension size in the feed-forward network.
            dropout (float): Dropout rate for regularization.
            sequence_length (int): Maximum sequence length the model is expected to process.
                                   Used for positional encoding and causal mask generation.
        """
        super().__init__()
        self.model_dim = model_dim
        self.sequence_length = sequence_length

        # Input projection to map input features to model_dim
        self.input_projection = nn.Linear(input_size, model_dim)
        
        # Positional Encoding to inject temporal information
        self.positional_encoding = FinancialPositionalEncoding(model_dim, max_len=sequence_length)
        self.dropout = nn.Dropout(dropout)

        # Stack of Transformer Encoder Blocks
        self.encoder_layers = nn.ModuleList([
            TransformerEncoderBlock(model_dim, num_heads, ff_dim, dropout)
            for _ in range(num_layers)
        ])
        
        # Pre-generate causal mask for efficiency, will be moved to device during forward pass
        self.causal_mask = FinancialAttention.generate_causal_mask(sequence_length)

        # Output layer
        # Layer normalization before the final output head
        self.output_norm = nn.LayerNorm(model_dim)
        # Linear layer to map the Transformer's output to the desired prediction size
        self.output_head = nn.Linear(model_dim, output_size)

        # Initialize model weights for better training stability
        self._init_weights()

    def _init_weights(self):
        """
        Initializes weights using Xavier uniform for linear layers and Glorot uniform for embeddings.
        Bias terms are set to zero, and layer norm weights to one.
        """
        for name, p in self.named_parameters():
            if p.dim() > 1 and ('linear' in name or 'projection' in name or 'head' in name):
                nn.init.xavier_uniform_(p)
            elif 'norm' in name and 'bias' in name:
                nn.init.zeros_(p)
            elif 'norm' in name and 'weight' in name:
                nn.init.ones_(p)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass of the AegisEvolution model.

        Args:
            x (torch.Tensor): Input tensor of financial time series data.
                              Shape: [batch_size, seq_len, input_size].

        Returns:
            torch.Tensor: Model's prediction. By default, it returns the prediction
                          for the last time step in the sequence.
                          Shape: [batch_size, output_size].
        """
        # Ensure causal_mask is on the same device as the input tensor
        causal_mask = self.causal_mask.to(x.device)
        
        # Input Projection and scaling
        x = self.input_projection(x) * math.sqrt(self.model_dim)

        # Add positional encoding and apply dropout
        x = self.positional_encoding(x)
        x = self.dropout(x)

        # Pass through the stack of Transformer Encoder Blocks
        for encoder_layer in self.encoder_layers:
            x = encoder_layer(x, causal_mask=causal_mask)
        
        # Apply layer normalization before the final output head
        x = self.output_norm(x)

        # For forecasting, typically the output of the last time step is used
        # to make predictions. If multiple predictions per step are needed,
        # the output head would apply to 'x' directly.
        output = self.output_head(x[:, -1, :])

        return output