# Auto-generated by AEGIS 4.0 on 2026-02-19 23:40:49.407998
import torch
import torch.nn as nn
import math

import torch
import torch.nn as nn
import math

class AegisEvolution(nn.Module):
    def __init__(self, input_size: int, d_model: int = 128, nhead: int = 4,
                 num_encoder_layers: int = 2, dim_feedforward: int = 512,
                 dropout: float = 0.1, output_size: int = 1):
        """
        Initializes the AegisEvolution model, a Transformer-based architecture
        designed for improved performance and optimized for MacBook M5 MPS acceleration.

        Args:
            input_size (int): The number of features in the input data (shape: Batch, input_size).
                              This will be projected into the `d_model` dimension.
            d_model (int): The embedding dimension for the Transformer. Must be divisible by `nhead`.
            nhead (int): The number of attention heads in the MultiheadAttention mechanism.
            num_encoder_layers (int): The number of stacked `TransformerEncoderLayer` instances.
            dim_feedforward (int): The dimension of the feedforward network within each
                                   `TransformerEncoderLayer`.
            dropout (float): The dropout probability applied in the Transformer encoder layers.
            output_size (int): The desired dimension of the model's output (e.g., number of classes).
        """
        super().__init__()

        # Ensure d_model is divisible by nhead as required by MultiheadAttention
        if d_model % nhead != 0:
            raise ValueError(f"d_model ({d_model}) must be divisible by nhead ({nhead}) for MultiheadAttention.")

        self.input_size = input_size
        self.d_model = d_model
        self.output_size = output_size

        # Input Projection Layer: Maps the flat input features to the transformer's embedding dimension.
        self.input_projection = nn.Linear(input_size, d_model)

        # Transformer Encoder: Processes the embedded input.
        # The input is treated as a sequence of length 1, where the single token represents
        # the entire input vector after projection.
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True,  # Ensures input/output tensors are (Batch, Seq, Feature)
            activation=nn.GELU() # GELU is a common activation function in modern Transformers
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_encoder_layers
        )

        # Output Layer: Projects the Transformer's output to the final desired output size.
        self.output_layer = nn.Linear(d_model, output_size)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Defines the forward pass for the AegisEvolution model.

        Args:
            x (torch.Tensor): Input tensor of shape (Batch, Input_Size).
                              For optimal performance on MacBook M5, ensure the tensor
                              and the model are moved to the 'mps' device (e.g., `model.to('mps')`,
                              `input_tensor.to('mps')`) during runtime.

        Returns:
            torch.Tensor: Output tensor of shape (Batch, Output_Size).
        """
        # (Batch, Input_Size) -> (Batch, d_model)
        x = self.input_projection(x)

        # (Batch, d_model) -> (Batch, 1, d_model)
        # Adds a sequence dimension of 1, treating the embedded input as a single token.
        x = x.unsqueeze(1)

        # (Batch, 1, d_model) -> (Batch, 1, d_model)
        # TransformerEncoder processes the single token.
        x = self.transformer_encoder(x)

        # (Batch, 1, d_model) -> (Batch, d_model)
        # Removes the sequence dimension before the final output projection.
        x = x.squeeze(1)

        # (Batch, d_model) -> (Batch, Output_Size)
        # Final projection to the desired output dimension.
        x = self.output_layer(x)

        return x