# Auto-generated by AEGIS 4.0 on 2026-02-19 15:08:50.600465
import torch
import torch.nn as nn

import torch
import torch.nn as nn
import math

class GatedResidualNetwork(nn.Module):
    """
    Gated Residual Network (GRN) as used in TFT.
    Applies a MLP, then a GLU, then a residual connection.
    """
    def __init__(self, input_size, hidden_size, output_size=None, dropout_rate=0.1):
        super().__init__()
        output_size = output_size if output_size is not None else input_size
        self.input_size = input_size
        self.output_size = output_size
        self.hidden_size = hidden_size

        self.layernorm = nn.LayerNorm(input_size)
        self.dense_layer = nn.Linear(input_size, hidden_size)
        self.glu_layer = nn.Linear(hidden_size, 2 * output_size)
        self.dropout = nn.Dropout(dropout_rate)
        
        # Linear layer for residual connection if input and output sizes differ
        self.residual_layer = nn.Linear(input_size, output_size) if input_size != output_size else None

    def forward(self, x):
        # x shape: (batch_size, seq_len, input_size) or (batch_size, input_size)
        
        # Layer norm on input
        x_norm = self.layernorm(x)

        # Dense layer
        dense_out = torch.relu(self.dense_layer(x_norm))

        # GLU
        glu_out = self.glu_layer(dense_out)
        gate = torch.sigmoid(glu_out[..., :self.output_size])
        feature_transform = glu_out[..., self.output_size:]
        glu_gated = gate * feature_transform

        # Dropout
        glu_gated = self.dropout(glu_gated)
        
        # Residual connection
        if self.residual_layer is not None:
            residual = self.residual_layer(x)
        else:
            residual = x

        return residual + glu_gated

class TimeAwarePositionalEncoding(nn.Module):
    """
    Learned positional encoding for time-series data.
    Allows injecting time-specific information.
    """
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        self.pe = nn.Parameter(torch.empty(max_len, d_model))
        nn.init.uniform_(self.pe, -0.02, 0.02) # Initialize learnable PE

    def forward(self, x):
        # x shape: (batch_size, seq_len, d_model)
        seq_len = x.size(1)
        # Add PE to input, broadcasting over batch. Ensure PE is on the same device as x.
        return x + self.pe[:seq_len, :].unsqueeze(0).to(x.device)

class AegisMultiHeadSelfAttention(nn.Module):
    """
    Multi-Head Self-Attention with causal masking, specialized for financial time-series.
    Incorporates ideas from TFT's interpretability and standard Transformer attention.
    """
    def __init__(self, d_model, num_heads, dropout=0.1):
        super().__init__()
        assert d_model % num_heads == 0, "d_model must be divisible by num_heads"
        self.d_k = d_model // num_heads
        self.num_heads = num_heads
        
        # Q, K, V projections and output projection
        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = nn.Linear(d_model, d_model)
        self.output_linear = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, query, key, value, padding_mask=None):
        # query, key, value shape: (batch_size, seq_len, d_model)
        batch_size = query.size(0)
        seq_len = query.size(1)

        # Apply linear projections and split into heads
        q = self.q_proj(query).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        k = self.k_proj(key).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        v = self.v_proj(value).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        # q, k, v shape: (batch_size, num_heads, seq_len, d_k)

        # Scaled Dot-Product Attention
        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.d_k)
        # scores shape: (batch_size, num_heads, seq_len, seq_len)

        # Causal Masking: Prevent attention to future time steps.
        # This creates a lower triangular mask.
        causal_mask = torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool), diagonal=1).to(scores.device)
        scores.masked_fill_(causal_mask, float('-inf'))

        # Apply padding mask if provided
        # padding_mask shape: (batch_size, seq_len) where True means masked (padding)
        if padding_mask is not None:
            # Expand padding_mask to (batch_size, 1, 1, seq_len) to mask keys
            expanded_padding_mask = padding_mask.unsqueeze(1).unsqueeze(2) # (batch_size, 1, 1, seq_len)
            scores = scores.masked_fill(expanded_padding_mask, float('-inf'))

        attn = torch.softmax(scores, dim=-1)
        attn = self.dropout(attn)

        x = torch.matmul(attn, v) # (batch_size, num_heads, seq_len, d_k)

        # Concatenate heads and apply final linear layer
        x = x.transpose(1, 2).contiguous().view(batch_size, -1, self.num_heads * self.d_k)
        return self.output_linear(x) # (batch_size, seq_len, d_model)

class AegisEncoderLayer(nn.Module):
    """
    A single encoder layer of AegisEvolution, incorporating GRN, Attention, and Residuals.
    """
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = AegisMultiHeadSelfAttention(d_model, num_heads, dropout)
        self.feed_forward = GatedResidualNetwork(d_model, d_ff, d_model, dropout) # Using GRN for FFN
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x, padding_mask=None):
        # Self-Attention Block
        attn_output = self.self_attn(x, x, x, padding_mask)
        x = x + self.dropout1(attn_output) # Residual connection
        x = self.norm1(x) # Layer Norm

        # Feed-Forward Block (GRN)
        ff_output = self.feed_forward(x)
        x = x + self.dropout2(ff_output) # Residual connection
        x = self.norm2(x) # Layer Norm
        return x

class AegisEvolution(nn.Module):
    """
    AegisEvolution: An improved PyTorch model based on Transformer/TFT architecture
    optimized for MacBook M5 MPS acceleration, with specialized attention for
    financial time-series and residual connections.
    """
    def __init__(self, input_size, d_model=128, num_heads=8, num_layers=3, d_ff=256, dropout=0.1, output_size=1, max_seq_len=5000):
        super().__init__()

        self.input_embedding = nn.Linear(input_size, d_model)
        self.positional_encoding = TimeAwarePositionalEncoding(d_model, max_len=max_seq_len)
        self.dropout = nn.Dropout(dropout)

        self.encoder_layers = nn.ModuleList([
            AegisEncoderLayer(d_model, num_heads, d_ff, dropout)
            for _ in range(num_layers)
        ])

        # Final prediction head. A GRN followed by a linear layer for output.
        self.output_grn = GatedResidualNetwork(d_model, d_ff, d_model, dropout)
        self.prediction_head = nn.Linear(d_model, output_size)

        # MPS optimization: Move model to MPS device if available at initialization.
        self.device = torch.device("cpu")
        if torch.backends.mps.is_available():
            self.device = torch.device("mps")
            print("MPS device found. AegisEvolution model will be initialized on MPS for acceleration.")
        else:
            print("MPS device not found. AegisEvolution model will run on CPU.")
        self.to(self.device)

    def forward(self, x, padding_mask=None):
        # x shape: (batch_size, seq_len, input_size)
        # padding_mask shape: (batch_size, seq_len) where True indicates padding to be masked out.

        # Ensure input tensor is on the correct device
        x = x.to(self.device)
        if padding_mask is not None:
            padding_mask = padding_mask.to(self.device)

        # Input Embedding
        x = self.input_embedding(x) # (batch_size, seq_len, d_model)

        # Positional Encoding
        x = self.positional_encoding(x)
        x = self.dropout(x)

        # Encoder Layers
        for layer in self.encoder_layers:
            x = layer(x, padding_mask) # (batch_size, seq_len, d_model)

        # Output GRN and Prediction Head
        # The model outputs a prediction for each time step.
        x = self.output_grn(x) # (batch_size, seq_len, d_model)
        predictions = self.prediction_head(x) # (batch_size, seq_len, output_size)

        return predictions